### ISSUE TITLE
[BE] Discuss Implementation of Web Annotation Data Model

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#370]
### Description

We have the discuss the implementation of Annotation Data Model to backend as backend team.

### Required Activities

- [x] Discuss how to implement
- [x] Note the ideas

### Estimated Time

2

### Deadline

12.11.2024

### Reviewer

@halil-ibrahim-kasapoglu

**Comment by rukiyeaslan** [comment]
We decided to follow the Web annotation model and transfer data in the format specified by web annotation model. An example for data would be:

> {
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "body": "http://example.org/post1",
  "target": "http://example.com/page1"
}

To achieve this, we will implement a new django app for annotations and manage all annotation related logic there so that it will be isolated from our existing implementation for our app.

cc @cemgungor1, @oguzpancuk

**Comment by cemgungor1** [comment]
This issue is closed and ready to be reviewed by @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
> We decided to follow the Web annotation model and transfer data in the format specified by web annotation model. An example for data would be:
> 
> > {
> > "@context": "http://www.w3.org/ns/anno.jsonld",
> > "id": "http://example.org/anno1",
> > "type": "Annotation",
> > "body": "http://example.org/post1",
> > "target": "http://example.com/page1"
> > }
> 
> To achieve this, we will implement a new django app for annotations and manage all annotation related logic there so that it will be isolated from our existing implementation for our app.
> 
> cc @cemgungor1, @oguzpancuk

I believe these are the ideas noted under the required activities in the description. Are you planning to document them or add them to the wiki? If not, I will go ahead and close this issue.
