### ISSUE TITLE
[FE] Integrate Post Creation Modal with Backend  

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#392]
### **Description**  

To enable seamless post creation, we need to integrate the frontend **Post Modal Page** with the backend service. This task involves connecting the UI components to the backend API endpoints, ensuring that posts created on the frontend are stored correctly in the database. The integration should handle user inputs for title, tags, portfolios, news, text ideas, line charts, and other required fields.

### **Required Activities**  
- [x] Connect the **Post Modal Page** to backend APIs for creating posts.  
- [ ] Implement form validation to ensure all required fields are provided.  
- [x] Handle API responses and display success or error messages to the user.  
- [x] Test the integration with sample data to confirm functionality.  

### **Estimated Time**  
8 hours  

### **Deadline**  
20 Nov 2024  

### **Reviewer**  
@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
Created Create Post Page for this purpose. Title, description, and partially tags are wanted as input. Other inputs will be implemented later. Since not all input fields are implemented, form validation have not been implemented. Although this version is merged, issue can be closed or kept open for full implementation after review of @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one, everything looks good to me
