### ISSUE TITLE
Research on Use Case Diagrams

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#90]
### Description

There is a need to conduct research on the listed topics below. There are several materials discovered that need to be consumed to complete the research.

### Research Topics

- Understand how to create use case diagrams
- Realize do's and dont's
- Check tools to create use case diagrams and select the most suitable one for our needs.

### Materials to Consume

- Moodle slides
### Tools 
- [PlantUML](https://plantuml.com/)
- [draw.io](https://app.diagrams.net/)
- [Lucidchart](https://www.lucidchart.com/pages/)

### Acceptance Criteria

- [ ] Materials are consumed

### Deadline

23 March 2024

**Comment by furkansenkal** [comment]
I checked each website listed above, read some documentation, and watched a few videos on what is a use case diagram and how can we create it. After my research, I think we should use Lucidchart to create our use case diagrams since it is easy to understand and use.

Here is a [video](https://www.youtube.com/watch?v=4emxjxonNRI) that explains use case diagrams using Lucidchart.
