### ISSUE TITLE
Plan Use Case Diagrams

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#92]
It is needed to define use cases for use case diagrams before creating them. The assignee of this task should make an analysis of what kind of use case diagrams we will have. Provide a list of use case diagram names in the comments.

### Reviewer 
@furkansenkal 

### Deadline 
25 March 2024

**Comment by iremnuy** [comment]
I read about use-case diagrams and suggest everyone to look at this [website](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-use-case-diagram/) to get familiar with the use-cases which will helps us a lot to abstract our system's interactions with various actors. I defined our potential actors that we will either be serving or be served by (such as browsers).You can find our initial draw.io template at our project repo.

Actors can be anyone that our system will have any kind of interaction with, we should ask ourselves the following questions to elicitate our actors.

- Who uses the system?
- Who installs the system?
- Who starts up the system?
- Who maintains the system?
- Who shuts down the system?
- What other systems use this system?
- Who gets information from this system?
- Who provides information to the system?
- Does anything happen automatically at a present time?

So defining them is a good starting point for defining the overall use-case diagrams.I suggest to decide on actors at our next meeting so that we can then define their actions-functions accurately.

Also some important headlines that we should discuss are:

- System boundary ( which defines the overall frame of the system, its scope )

- Extend-Include relationships, where we have which one of them etc.

**Comment by iremnuy** [comment]
Planning process helped me a lot, I created and added use case diagrams to our repo.

**Comment by furkansenkal** [comment]
I reviewed your work. It is crystal clear explained and helped us a lot before discussion. Well done!
